# Generated by Django 4.1.3 on 2022-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_holding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='holding_date',
            field=models.DateField(default='2022-12-12'),
            preserve_default=False,
        ),
    ]
