# Generated by Django 4.1.3 on 2022-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'verbose_name_plural': 'Hours'},
        ),
        migrations.AlterField(
            model_name='meetingurl',
            name='behance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingurl',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingurl',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingurl',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
