# Generated by Django 4.1.1 on 2022-11-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_hours_options_alter_meetingurl_behance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='hours',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingurl',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='meetings.meeting'),
        ),
    ]
