# Generated by Django 4.1.1 on 2022-11-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meeting_listeneres_meeting_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='listeneres',
            new_name='listeners',
        ),
    ]
